import "server-only";

import { readFileSync } from "node:fs";
import path from "node:path";

/**
 * Entity names and kinds from the pipeline's crosswalk (pipeline/geo/entities.csv, built from Natural Earth, public
 * domain), copied into .generated by scripts/sync-data.mjs. Unknown codes throw: a name is never guessed.
 */
type Entity = { iso3: string; name: string; kind: string };

let cache: Map<string, Entity> | null = null;

function parseCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (quoted) {
      if (ch === '"' && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else if (ch === '"') quoted = false;
      else cur += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ",") {
      out.push(cur);
      cur = "";
    } else cur += ch;
  }
  out.push(cur);
  return out;
}

function table(): Map<string, Entity> {
  if (cache) return cache;
  const text = readFileSync(path.join(process.cwd(), ".generated", "v1", "entities.csv"), "utf8");
  const [header, ...rows] = text.trim().split("\n");
  const cols = parseCsvLine(header);
  const [iC, nC, kC] = ["iso3", "name", "kind"].map((c) => cols.indexOf(c));
  if (iC < 0 || nC < 0 || kC < 0) throw new Error("entities.csv: missing iso3, name or kind column");
  cache = new Map(
    rows.map((r) => {
      const v = parseCsvLine(r);
      return [v[iC], { iso3: v[iC], name: v[nC], kind: v[kC] }];
    }),
  );
  return cache;
}

export function entityName(code: string): string {
  const e = table().get(code);
  if (!e) throw new Error(`Unknown entity ${code}: not in pipeline/geo/entities.csv`);
  return e.name;
}

/** A country or territory (not an aggregate, station or producer pseudo-entity). */
export function isPlace(code: string): boolean {
  const e = table().get(code);
  if (!e) throw new Error(`Unknown entity ${code}: not in pipeline/geo/entities.csv`);
  return e.kind === "country" || e.kind === "territory";
}
